name: deploy-heroku

on: workflow_dispatch

jobs:
  deploy-heroku:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Docker Buildx
        id: setup_buildx
        uses: docker/setup-buildx-action@v1
        with:
          driver: docker
          install: true

      - name: Build-Push-Release App to Heroku
        env:
          DYNAMIC_ENV_FILEID: ${{ secrets.DYNAMIC_ENV_FILEID }}
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
          HEROKU_APP_NAME: ${{ secrets.HEROKU_APP_NAME }}
        run: |
          heroku container:login
          echo "FROM ghcr.io/ksssomesh12/tgmb-beta:master
          COPY . .
          " >> Dockerfile
          echo "https://docs.google.com/uc?export=download&id=$DYNAMIC_ENV_FILEID" | aria2c --input-file=-
          docker build . -t registry.heroku.com/$HEROKU_APP_NAME/worker --progress=plain
          docker push registry.heroku.com/$HEROKU_APP_NAME/worker
          heroku container:release worker -a $HEROKU_APP_NAME
